
package pl.lodz.p.it.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapUserServiceService", targetNamespace = "http://impl.it.p.lodz.pl/", wsdlLocation = "http://localhost:8080/Store/SoapUserServiceService?wsdl")
public class SoapUserServiceService
    extends Service
{

    private final static URL SOAPUSERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPUSERSERVICESERVICE_EXCEPTION;
    private final static QName SOAPUSERSERVICESERVICE_QNAME = new QName("http://impl.it.p.lodz.pl/", "SoapUserServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Store/SoapUserServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPUSERSERVICESERVICE_WSDL_LOCATION = url;
        SOAPUSERSERVICESERVICE_EXCEPTION = e;
    }

    public SoapUserServiceService() {
        super(__getWsdlLocation(), SOAPUSERSERVICESERVICE_QNAME);
    }

    public SoapUserServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPUSERSERVICESERVICE_QNAME, features);
    }

    public SoapUserServiceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPUSERSERVICESERVICE_QNAME);
    }

    public SoapUserServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPUSERSERVICESERVICE_QNAME, features);
    }

    public SoapUserServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapUserServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapUserServiceInterface
     */
    @WebEndpoint(name = "SoapUserServicePort")
    public SoapUserServiceInterface getSoapUserServicePort() {
        return super.getPort(new QName("http://impl.it.p.lodz.pl/", "SoapUserServicePort"), SoapUserServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapUserServiceInterface
     */
    @WebEndpoint(name = "SoapUserServicePort")
    public SoapUserServiceInterface getSoapUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.it.p.lodz.pl/", "SoapUserServicePort"), SoapUserServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPUSERSERVICESERVICE_EXCEPTION!= null) {
            throw SOAPUSERSERVICESERVICE_EXCEPTION;
        }
        return SOAPUSERSERVICESERVICE_WSDL_LOCATION;
    }

}
